#!/bin/sh
# Update UFO after editing with FontForge and prior to commit

# Stop on any errors
set -e

# Check and normalize all UFOs first -- assumes no other steps de-normalize
echo "Fixing FontForge debris and normalizing UFOs..."
psffixffglifs -p checkfix=fix source/masters/*-Regular.ufo  &
psffixffglifs -p checkfix=fix source/masters/*-Bold.ufo     &
wait

echo "Updating glyph orders in Regular..."
psfsetglyphorder -q -p checkfix=none -p backup=False --header DesignerOrder,DesignerOrder --field public.glyphOrder,com.schriftgestaltung.glyphOrder -i source/glyph_data.csv source/masters/*-Regular.ufo

echo "Updating production names in Regular..."
psfsetpsnames -q -p checkfix=none -p backup=False -i source/glyph_data.csv source/masters/*-Regular.ufo

echo "Syncing glyph orders, psnames, and other metadata to other UFOs..."
psfsyncmasters -q source/*.designspace

echo "Updating woff metadata files..."
psfmakewoffmetadata -q -n "ScheherazadeNew" -i org.sil.fonts source/masters/*-Regular.ufo -o "source/ScheherazadeNew-WOFF-metadata.xml"

echo "Building internal fea..."
psfmakefea -q -o source/masters/ScheherazadeNew-Regular.ufo/features.fea -l source/logs/ScheherazadeNew-Regular-psfmakefea.log -i source/opentype/main.feax --omitaps "_above,_below,_center,_ring,_through,above,below,center,ring,through,U,L,O" source/masters/*-Regular.ufo &
psfmakefea -q -o source/masters/ScheherazadeNew-Bold.ufo/features.fea    -l source/logs/ScheherazadeNew-Bold-psfmakefea.log    -i source/opentype/main.feax --omitaps "_above,_below,_center,_ring,_through,above,below,center,ring,through,U,L,O" source/masters/*-Bold.ufo    &
wait

echo "preflightff completed!"
