#!/bin/sh
# Update UFO after any edits other than with FontForge and prior to commit

# Stop on any errors
set -e

# Check and normalize all UFOs first -- assumes no other steps de-normalize
echo "Normalizing UFOs..."
psfnormalize -p checkfix=fix source/masters/*-Regular.ufo  &
psfnormalize -p checkfix=fix source/masters/*-Bold.ufo    &
wait

echo "Updating woff metadata xml file..."
psfmakewoffmetadata -q -n ScheherazadeNew -i org.sil.fonts source/masters/*-Regular.ufo -o "source/ScheherazadeNew-WOFF-metadata.xml"

echo "Updating glyph orders in Regular..."
psfsetglyphorder -q -p checkfix=none -p backup=False --header DesignerOrder,DesignerOrder --field public.glyphOrder,com.schriftgestaltung.glyphOrder -i source/glyph_data.csv source/masters/*-Regular.ufo

echo "Updating production names in Regular..."
psfsetpsnames -q -p checkfix=none -p backup=False -i source/glyph_data.csv source/masters/*-Regular.ufo

echo "Syncing glyph orders, psnames, and other metadata to other UFOs..."
psfsyncmasters -q source/*.designspace

echo "Building internal fea..."
psfmakefea -q -o source/masters/ScheherazadeNew-Regular.ufo/features.fea -l ScheherazadeNew-Regular-psfmakefea.log -i source/opentype/master.feax --omitaps "topright, ogonek, caret_1, caret_2, caret_3, top_1, top_2, top_3, top_4, top_alef, bottom_1, bottom_2" -c source/classes.xml source/masters/*-Regular.ufo &
psfmakefea -q -o source/masters/ScheherazadeNew-Bold.ufo/features.fea    -l ScheherazadeNew-Bold-psfmakefea.log    -i source/opentype/master.feax --omitaps "topright, ogonek, caret_1, caret_2, caret_3, top_1, top_2, top_3, top_4, top_alef, bottom_1, bottom_2" -c source/classes.xml source/masters/*-Bold.ufo   &
wait

echo "preflight completed!"
