#!/bin/sh
# Extract UFOs from .glyphs file, then do normal preflight.

# Create UFO from Glyphs file

echo ""
echo "Converting .glyphs to UFO3..."
if psfglyphs2ufo --nofea source/masters/Scheherazade-master.glyphs source/masters
then
  # Success. Now fix up the advance width of damma-ar.ss0
  psfremovegliflibkeys source/masters/Scheherazade-Regular.ufo com.schriftgestaltung.Glyphs.originalWidth
  psfremovegliflibkeys source/masters/Scheherazade-Bold.ufo    com.schriftgestaltung.Glyphs.originalWidth
  ./preflight
else
  # Something went wrong... abort
  echo ""
  echo "psfglyphs2ufo failed ... aborting preflightg"
  echo ""
fi
