#!/bin/sh
# script to convert UFOs to glyphs file for editing

# Create UFO from Glyphs file
echo
echo "Converting UFO3 to .glyphs..."
psfufo2glyphs source/Scheherazade.designspace source/masters/Scheherazade-master.glyphs -l source/logs/ufo2g.log
