#!/bin/sh
# script to convert UFOs to glyphs file for editing

echo
echo "Converting UFO3 to .glyphs..."
psfufo2glyphs --nofea source/ScheherazadeNew.designspace source/masters/ScheherazadeNew.glyphs -l source/logs/ufo2g.log
